### ISSUE TITLE
First person rule seems to be triggered by "API"

### ISSUE THREAD

**Issue by felicity-semmle** [errata-ai/Microsoft#11]
```
<p>In addition, the integration can accept POST requests made to the LGTM endpoint and use them to hide alerts in some views of the <MadCap:variable name="Variables.ShortProductName" /> application. For full details of the webhook API calls, see <MadCap:xref href="issuetracker-webhook-api.html">Issue tracker webhook API</MadCap:xref>. For an example webhook receiver, see <a href="https://github.com/Semmle/lgtm-issue-tracker-example" target="_blank" class="externalLink">LGTM Issue Tracker Example</a>. This repository contains a basic application that is set up to pass information between LGTM and an issue tracker.</p>
```

(Apologies for the long line. Madcap Flare doesn't have any controls over line length.)
This triggered the following warning:

``` 
16:242  warning     Use first person sparingly      Microsoft.FirstPerson    
                     ('I'). 
 ```

Possibly I'm doing something wrong with my `.ini` file but I couldn't see anything that would affect this result.

**Comment by polarweasel** [comment]
Here are my results with that text, with vale set to `MinAlertLevel = suggestion`:

```bash
alex.ball:~/devel$ pbpaste | vale
 stdin.txt
 1:70   suggestion  'LGTM' has no definition.       Microsoft.Acronyms     
 1:475  suggestion  'LGTM' has no definition.       Microsoft.Acronyms     
 1:523  suggestion  Consider using 'has' instead    Microsoft.ComplexWords 
                    of 'contains'
 1:552  error       Use "that's" instead of "that   Microsoft.Contractions 
                    is".                                                   
 1:557  suggestion  'is set' looks like passive     Microsoft.Passive      
                    voice.                                                 
 1:595  suggestion  'LGTM' has no definition.       Microsoft.Acronyms     
✖ 1 error, 0 warnings and 5 suggestions in stdin.
```

**Comment by felicity-semmle** [comment]
Thanks for responding so quickly. I wonder why you don't get the same error that I'm seeing. I've also run it on the output file generated by Flare and get the same error there (even when the variable is replaced with plain HTML).

I'm not sure how to debug this - any suggestions?

**Comment by felicity-semmle** [comment]
@polarweasel suggested that I try this in a standalone text file - which is what he did. This gave me the following results:
```
 test.html
 1:1    suggestion  Grade level (10.54) too high!   Semmle.Readability
 1:234  warning     Use first person sparingly      Microsoft.FirstPerson
                    ('I').
 1:523  suggestion  Consider using 'has' instead    Microsoft.ComplexWords
                    of 'contains'
 1:552  suggestion  Use "that's" instead of "that   Microsoft.Contractions
                    is".
 1:557  warning     'is set' looks like passive     Microsoft.Passive
                    voice.

✖ 0 errors, 2 warnings and 3 suggestions in 1 file.
```
I don't get the acronymns warning because I've added "LGTM" to our acronyms file.

I'm using Windows 10, running Vale in a Git bash window and am using Vale 1.4.0 and a recent version of the Microsoft rules.

**Comment by jdkato** [comment]
This is indeed a bug (introduced in aae69299069191ef9e9a68b52211ee17966da166). I'll push a fix soon.

(@polarweasel is probably using an older release of the style, which had other issues with `Microsoft.FirstPerson` that aae69299069191ef9e9a68b52211ee17966da166 tried to fix.)

**Comment by polarweasel** [comment]
Glad to know laziness has paid off for me in this case :)

**Comment by felicity-semmle** [comment]
Thanks for responding so quickly - I only wish commercial software was as well supported!

**Comment by jdkato** [comment]
This should be fixed in the [latest release](https://github.com/errata-ai/Microsoft/releases).

**Comment by felicity-semmle** [comment]
Wow! Many thanks. 

I'll install the new version first thing tomorrow morning (I'm in the UK and have to dash for an evening meeting).

**Comment by felicity-semmle** [comment]
Works perfectly with your change. Many thanks 😄
