### ISSUE TITLE
FirstPerson.yml is missing a check for "mine", "we", "ours"

### ISSUE THREAD

**Issue by dylan-k** [errata-ai/Microsoft#12]
First person possessive and plural words are missing from the first person check.

**Comment by jdkato** [comment]
Thanks for the report.

I'd estimate that we currently have around 40% coverage of the style guide, so there's definitely still a lot to implement.

**Comment by markekraus** [comment]
some additional first person-plurals:

- our
- let's
- us
- we're
- we've

**Comment by jdkato** [comment]
Thanks&mdash;I'm hoping to get another release out soon that includes this and some other enhancements.
