### ISSUE TITLE
Microsoft.Units error on Minutes

### ISSUE THREAD

**Issue by markekraus** [errata-ai/Microsoft#17]
Per https://docs.microsoft.com/en-us/style-guide/numbers

> Spell out zero through nine and use numerals for 10 or greater for days, weeks, and other units of time.
Examples
seven years
28 days
12 hrs

Which means 0-9 minutes should be words and not numerals.

```bash
echo 'It takes three minutes to cook ramen noodles.' | vale --no-wrap -ext='.md'
```

Output

```none
 stdin.md
 1:10  error  Use a numeral plus the units.  Microsoft.Units 

✖ 1 error, 0 warnings and 0 suggestions in stdin.
```

**Comment by jdkato** [comment]
Thanks for the report. 

It looks like 'minutes' should be removed from the rule and the link should be changed to [Units of measure](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/term-collections/units-of-measure-terms):

> Use numerals for measurements of distance, temperature, volume, size, weight, pixels, points, and so on—even if the number is less than 10. Add a zero before the decimal point for decimal fractions less than one, unless the customer is asked to enter the value.
