### ISSUE TITLE
Get "Don't spell out the number 'a cm'" when using the word "cmdlet"

### ISSUE THREAD

**Issue by markwragg** [errata-ai/Microsoft#19]
Cmdlet is a common PowerShell word. The linter has recently started to flag its usage as an error, saying 

```
Don't spell out the number in 'a cm'.  Microsoft.Units
```

Sample input text:
>  Using a task is similar to using a cmdlet or a function call.

**Comment by jdkato** [comment]
This should be fixed in the latest release.
