### ISSUE TITLE
Ordinal Date false capture bug

### ISSUE THREAD

**Issue by brandonkal** [errata-ai/Microsoft#25]
This regex marks the word "of" as an ordinal number. There may be other cases.

> May of 2013

Results in the error: Don't use ordinal numbers for dates

https://github.com/errata-ai/Microsoft/blob/00eeb71180c72e6e85faeca0434eaaa861e805b4/Microsoft/DateNumbers.yml#L7

**Comment by amyq** [comment]
@esmerel and I have hit this bug too.

**Comment by jdkato** [comment]
The best solution here is probably to just go through and enumerate the first 31 ordinal numbers. I'd probably use a rule structure similar to [Passive](https://github.com/errata-ai/Microsoft/blob/00eeb71180c72e6e85faeca0434eaaa861e805b4/Microsoft/Passive.yml) to avoid having one long line.
