### ISSUE TITLE
End punctuation

### ISSUE THREAD

**Issue by brandonkal** [errata-ai/Microsoft#26]
A heading like "8. Do step eight" throws an error. I assume the intent was to catch the character when used as sentence punctuation. This is also an issue with Google styles.

**Comment by jdkato** [comment]
It's worth noting that this doesn't "throw an error"; it's a [warning-level rule](https://github.com/errata-ai/Microsoft/blob/master/Microsoft/HeadingPunctuation.yml). There's also an [open issue to clarify this point in the guide](https://github.com/MicrosoftDocs/microsoft-style-guide/issues/23).

In any case, the "fix" here is quite simple: remove `0-9` from the character class.
