### ISSUE TITLE
Project name & Asciidoc

### ISSUE THREAD

**Issue by akosma** [errata-ai/Microsoft#27]
I am in a weird situation. I am adding documentation in Asciidoc format to a project named "Steward". According to the ["Microsoft.GenderBias" rule](https://github.com/errata-ai/Microsoft/blob/f2b193c9a81d529aaa58b9eda12a8ec22a52af2f/Microsoft/GenderBias.yml#L39), this is not accepted. Unfortunately `vale` does not accept [comment-based exceptions in Asciidoc files](https://errata-ai.github.io/vale/config/#ignoring-parts-of-your-documents). The project name cannot be changed, nor can the documentation format.

What would you suggest to do? My current plan is to fork this project, and remove this rule, as I cannot think of any other solution.

**Comment by jdkato** [comment]
You could simply disable the rule in your config file (`Microsoft.GenderBias = NO`) rather than having to maintain a fork.

I'd like to support comment-based exceptions in Asciidoc files but, unlike the other formats, it didn't (and as far as I know, still doesn't) offer a means of preserving comments in HTML output.

**Comment by akosma** [comment]
Thanks for the answer! For the moment I'm going to disable the rule as you suggest.

Regarding the comment-based exception, I'm pretty sure you've already considered it, but maybe the passthrough macro might help in this case? https://asciidoctor.org/docs/user-manual/#passthroughs

Thanks for the help!

**Comment by akosma** [comment]
Just for the record, tried this and it worked:

```asciidoc
pass:[<!-- vale Microsoft.GenderBias = NO -->] 

This steward is ignored.

pass:[<!-- vale Microsoft.GenderBias = YES -->]

This is a steward that raises an alert.
```

Hope this helps!

**Comment by akosma** [comment]
It also works inline, as expected.

**Comment by jdkato** [comment]
Thanks -- I'll add a note to the docs about this.
