### ISSUE TITLE
False positives for ComplexWords rule

### ISSUE THREAD

**Issue by koenvervloesem** [errata-ai/Microsoft#36]
I have a sentence using "address bar". The ComplexWords rule of the Microsoft style suggests to use 'discuss' instead of 'address'. I tried to add "address bar" to `accept.txt` in my vocabulary, but the rule still flags it. Am I using this wrong or is this an error in Vale and/or the Microsoft style?

**Comment by jdkato** [comment]
This isn't an error, really. Many of the `suggestion`-level alerts only look for the presence of a word/phrase without considering the context.

If you find this more bothersome than helpful, you can either disable a specific rule (in this case, `ComplexWords`) or raise the `MinAlertLevel`.

**Comment by koenvervloesem** [comment]
Right, but my question was more about the correct way to add exceptions to the rule (I should have made this clearer in the title of this issue). After reading https://docs.errata.ai/vale/vocab I thought that by adding "address bar" or "IP address" to the `accept.txt` file for my Vocab, Vale would ignore these word groups for the `ComplexWords` rule. Am I reading this wrong?
