### ISSUE TITLE
Microsoft.Headings "sentence-style capitalization" for brands with hyphen

### ISSUE THREAD

**Issue by BenRoe** [errata-ai/Microsoft#39]
Hello,
i have a heading like `Build guide for the Plaid-Pad` and added the Plaid-Pad to my `accept.txt`, but the suggestion is still triggered.
How can i avoid that, without disabling the Headings rule?

**Comment by jdkato** [comment]
This is https://github.com/errata-ai/vale/issues/346. As a workaround, you could:

- Selectively disable the rule for that heading with a [comment](https://docs.errata.ai/vale/scoping#markup-based-configuration).
- Add either (or both) of the terms individually. 
- Write a [`TokenIgnores`](https://docs.errata.ai/vale/scoping#non-standard-markup) pattern, such as `TokenIgnores = (Plaid-Pad)`.

**Comment by JamesDuff2021** [comment]
Hello! I have a similar problem. We've been working on a Vale rule that enforces sentence style capitalization. We have included a few exceptions for some proper nouns that we use. Everything seems to be working well, except for some terms with hyphens. Here is the rule:
extends: capitalization
message: "'%s' should use sentence-style capitalization."
level: warning
match: $sentence
threshold: 0.9
exceptions:
  - Package Builder
  - High-Def Render Pipeline
  - H-Def Render Pipeline
  - High Definition Render Pipeline
Vale allows all exceptions except for: High-Def Render Pipeline. I've tried a bunch of other terms with hyphens and as long as the first part of the word is more than 1 character, it doesn't work as an exception. Do you have any idea why this one exception is not working or any suggestions to get it working?

**Comment by jdkato** [comment]
This should be fixed in newer versions of Vale.
