### ISSUE TITLE
Improve acronyms rule to match defined acronyms

### ISSUE THREAD

**Issue by politician** [errata-ai/Microsoft#44]
The [Microsoft guide says](https://docs.microsoft.com/en-us/style-guide/acronyms#if-you-have-to-use-an-acronym-also-spell-out-the-term-for-clarity) that acronyms shouldn't be used unless they are spelled out. However, the current Vale rule does not allow for this.

**Actual behavior:**

![Screenshot 2022-06-23 at 13 38 12](https://user-images.githubusercontent.com/3155568/175231817-f91a4c8b-c3c2-4b55-9a8c-df6eb3ebe155.png)

**Expected behavior:**

Because **p**ersonal **a**ccess **t**oken is spelled out just before the use of the acronym, it should not fail.

**Comment by jdkato** [comment]
The current implementation expects the definition's case to match, for example,

> You must use a Personal Access Token (PAT).

would yield no alert.

**Comment by politician** [comment]
You are right, I had actually tried it but it didn't work because my markdown formatter put it on the next line. I guess that's too much of an edge case to bother.
 
![Screenshot 2022-06-24 at 11 13 04](https://user-images.githubusercontent.com/3155568/175460853-406e7e81-7958-4891-934e-6762ee222c38.png)

**Comment by politician** [comment]
I just made sure that the parser could pick it up, it does and it even recognizes my next usage of PAT. Great!

![Screenshot 2022-06-24 at 11 18 29](https://user-images.githubusercontent.com/3155568/175461338-3cf44ca8-ed1f-487d-a16a-4565901c1b75.png)
