### ISSUE TITLE
"that is" suggested instead of i.e. but then flagged to be contracted

### ISSUE THREAD

**Issue by Fuco1** [errata-ai/Microsoft#45]
Maybe if the `that is` is followed by a comma we could ignore it and not suggest a contraction.

**Comment by blizzy78** [comment]
Yes, please change it such that `that is,` will be ignored. As an example, it should not suggest a contraction in this sentence:

```
AllMatch returns true if pred returns true for all elements produced by prod, that is, all elements match.
```
