### ISSUE TITLE
Duplicated tokens in `Terms.yml`

### ISSUE THREAD

**Issue by kayx23** [errata-ai/Microsoft#48]
https://github.com/errata-ai/Microsoft/blob/26acca62396038d7c46a56ea631c2a5261edf767/Microsoft/Terms.yml#L27-L30

Saw some of these tokens are duplicated. What was the intention?

**Comment by jdkato** [comment]
Nope, PRs welcome.

**Comment by kayx23** [comment]
@jdkato Opened PR
