### ISSUE TITLE
Understand `URL for` and `URL of` in `URLFormat.yml`

### ISSUE THREAD

**Issue by kayx23** [errata-ai/Microsoft#49]
https://github.com/errata-ai/Microsoft/blob/26acca62396038d7c46a56ea631c2a5261edf767/Microsoft/URLFormat.yml#L7-L9

I want to understand why `URL for` is recommended over `URL of`. Both seem to be reasonable.

`URL of` can be used to refer to the specific location of a webpage or resource, while `URL for` can be used to refer to the purpose or function of a web address or link.

**Comment by jdkato** [comment]
I've added a `link` and made this a `suggestion`.
