### ISSUE TITLE
Set acceptable acronyms and initialisms in headers

### ISSUE THREAD

**Issue by iainelder** [errata-ai/Microsoft#54]
Is there way to do this?

Some technical acryonyms and initialisms are better understood than the phrases they stand in for.

[XML](https://learn.microsoft.com/en-us/dotnet/standard/data/xml/)? [JSON](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-jsonl)? [SQL](https://learn.microsoft.com/en-us/azure/azure-sql/azure-sql-iaas-vs-paas-what-is-overview?view=azuresql)? Not even Microsoft spells these out. JSON is already pronounced as "jason" and SQL as "sequel".

As a workaround I can just disable this rule.

```ini
Microsoft.HeadingAcronyms = NO
```

With an acceptance list it could help to keep uncommon jargon out of headers.

**Comment by jdkato** [comment]
You can do this with a custom [vocabulary](https://vale.sh/docs/topics/vocab/).

It probably would also be useful to ignore some of the well-known ones by default.

**Comment by iainelder** [comment]
Thanks, @jdkato. I already use a custom vocabulary for spellchecking.

I don't see how it helps with the HeadingAcronyms rule.

Do I need to change a setting?

**Comment by jdkato** [comment]
If you have a term, such as "JSON," in your `accept.txt` it won't be reported by `Microsoft.HeadingAcronyms`.

**Comment by iainelder** [comment]
It works for me! Thanks.
